### ISSUE TITLE
Automatic URL Not working in IE/Edge or Mobile Browsers

### ISSUE THREAD

**Issue by RADRaze2KX** [t2t2/obs-tablet-remote#1]
When attempting to connect using the automatic URL, works fine in Firefox and Google Chrome for Windows:
http://t2t2.github.io/obs-tablet-remote/#!auto&host={remote_url}&password={password}

When attempting to connect using IE/Edge, or Chrome for Android, Free Adblock Browser, does not connect using the specified parameters, just directs to Usage Instructions screen to fill out the information manually.

**Comment by t2t2** [comment]
Looks like it was actually a bug that broke all auto connecting that didn't target default settings (localhost), fixed
