### ISSUE TITLE
Needs start stream button/function

### ISSUE THREAD

**Issue by jfreak53** [t2t2/obs-tablet-remote#2]
This is great but the one thing that would make it extremely useful would be a start/stop stream button somewhere. Otherwise all it does is switch between scenes.

**Comment by RADRaze2KX** [comment]
This would definitely be a huge plus to the interface. You are the man, t2t2!

**Comment by daniep01** [comment]
I agree, this is great and works beautifully but start/stop is really needed as well.

**Comment by garcia** [comment]
Sorry to bump with nothing but a +1, but... +1.  Having stream start/stop buttons is the only thing preventing me from using this for remote streaming.

**Comment by wreyniers** [comment]
Love this tool. This feature would be perfect.

+1!

**Comment by t2t2** [comment]
Now available with the modular update (layout edit mode -> add panel -> stream status)

**Comment by wreyniers** [comment]
NICE!

Thanks @t2t2
