### ISSUE TITLE
Layout editor not working on my tablet

### ISSUE THREAD

**Issue by Pumpk1in** [t2t2/obs-tablet-remote#21]
Hi :)

The layout editor not fully working : I can't edit the column sizes.
The touch event is not firing and instead, it's selecting the dots.

I'm running on Android 6.0.1, Firefox 57. Same thing occurs with the latest Chrome, or the latest Opera.

No problem with my phone, running on Android 7.0 and the same Firefox/Chrome/Opera.
Android 6.0.1 issue ?

Thanks !

**Comment by kaimi** [comment]
> Android 6.0.1 issue ?

Works for me™ on Android 7.1.2, latest Chrome. Do you have other Android devices / versions to test?
