### ISSUE TITLE
I can't scroll down

### ISSUE THREAD

**Issue by ther3y3s** [t2t2/obs-tablet-remote#42]
Hi, with new update, if i open it on a tablet, i can't scroll down so i can't use all my obs scenes...

**Comment by allycatty** [comment]
Have been using this for a couple months and i just started having this issue as well. tried to reset the layout now there's noting and I can't see the + to add anything. Using safari on ios9 (old ipad)

**Comment by t2t2** [comment]
Fixed layout issues in safari, if that isn't what is being meant please include screenshot.

**Comment by ther3y3s** [comment]
https://imgur.com/EoQc4kZ
u can see there are some others scenes but if i tried to scroll down page is blocked and so i can't see other scenes. I don't know if i make u understand what's the problem

**Comment by ther3y3s** [comment]
Man, sorry if i continue but still doesn't work for me

**Comment by t2t2** [comment]
Maybe forcing a refresh in web browser would help (in case old version is still cached), it's scrolling fine on my phone

https://gfycat.com/poisedellipticaldaddylonglegs
