### ISSUE TITLE
Cannot Adjust Payne Size for vertical splitter

### ISSUE THREAD

**Issue by scorpion313** [t2t2/obs-tablet-remote#43]
Went to use the remote tonight and for some reason, the vertical splitter will no longer allow me to adjust the payne size when editing the layout.  Horizontal works just fine still where it can be adjusted but not vertical.  I can adjust on my PC browser window but on my iPad and phone this no longer works.  Also, not sure if I noticed this before or not but for the mixer...  It shows ALL audio sources from ALL scenes/sources rather than just the current scene you're on.
![IMG_0044](https://user-images.githubusercontent.com/37963553/59155030-5c781800-8a4d-11e9-9a79-24bffa6559ff.PNG)

**Comment by t2t2** [comment]
Audio sources: Before only mic / desktop audio devices were listed, I did recently update the code for that to get more sources that output audio, yeah probably will add a way to filter to only sources that are on scene

**Comment by vilified** [comment]
Vk[]()
