### ISSUE TITLE
send recording events

### ISSUE THREAD

**Issue by thewayur** [t2t2/obs-tablet-remote#57]
i am very new to this project.

all i want to send recording events from my very own js file.

please instruct me

**Comment by t2t2** [comment]
[haganbmj/obs-websocket-js](https://github.com/haganbmj/obs-websocket-js) is better suitable for custom needs

**Comment by thewayur** [comment]
> [haganbmj/obs-websocket-js](https://github.com/haganbmj/obs-websocket-js) is better suitable for custom needs

thanks for the suggestion, 
yes i am using same right now. thanks again
