### ISSUE TITLE
Help building this on NPM (WIndows), hosting it privately and modifying the default layout

### ISSUE THREAD

**Issue by nnm103** [t2t2/obs-tablet-remote#66]
Hi everyone. I would really appreciate if someone can help with build this on a Windows machine (npm and nginx installed).  Whenever I try to build, I get errors.  NPM Install results in a bunch of warnings (ENOENT: no such file or directory) Error while executing ssh://git... 

NPM run build then also errors out ‘vue-cli-service’ is not recognized.  Basically, I need to get this hosted locally and then need to apply a different default layout.  

Thank you!

**Comment by t2t2** [comment]
Hard to tell without full log of `npm install` (and if that fails, build gonna fail too), but assuming from "Error while executing ssh://git" that error downloading a dependency over git

Can try replacing this line:

https://github.com/t2t2/obs-tablet-remote/blob/3da5587749df3092402f13968487f2d2ca2f560c/package.json#L40

with

```json
    "eslint-plugin-vue": "^6.0.0",
```

**Comment by nnm103** [comment]
Thank you @t2t2.  That worked; I did get some errors during the install, but the build worked.  I do need to modify the default view.  I have multiple users who need to access the remote and need to have one default review that is populated for them no matter what device they log in from.  Do you have a way / guide on how to create a layout and then set it as default or code it as default?

Thank you!

**Comment by t2t2** [comment]
Easiest is to probably create the layout yourself, then grab the JSON from localstorage (`localStorage.getItem('obs-remote-tablet-vuex')`) and then use `layout` field to fill out https://github.com/t2t2/obs-tablet-remote/blob/3da5587749df3092402f13968487f2d2ca2f560c/src/store/modules/layout/mutations.js#L16

**Comment by nnm103** [comment]
Thank you @t2t2.  Where can I found the local storage? I'm assuming I then modify the mutations.js and rebuild?

**Comment by t2t2** [comment]
Open developer tools in your browser of choice and either put `localStorage.getItem('obs-remote-tablet-vuex')` in console or find Storage tab (firefox) / Application (chrome).

And yes

**Comment by nnm103** [comment]
Thanks again @t2t2.  I am making progress, but when I modify the mutations.js it doesn't seem to apply the settings I have past panel id 2 for 'Scenes'.  Nothing shows up at the right.  can you take a look below.. what am I doing wrong?  I would also like to set the default to the dark-blue mode and make it login automatically without modifying the URL.  

Your help is highly appreciated!

```
state.nextId = 7
	state.panels = {
		1: {
			type: 'Grid',
			parent: null,
			settings: {direction: 'row'}
		},
		2: {
			type: 'Scenes',
			parent: 1,
			settings: {perRow: 1}
		},
		3: {
			type: 'Grid',
			parent: 1,
			settings: {direction: 'row'}
		},
		4: {
			type: 'Grid',
			parent: 3,
			settings: {direction: 'column'}
		},
		5: {
			type: 'Iframe',
			parent: 4,
			settings: {url: 'https://www.youtube.com/xxxx'}
		},
		6: {
			type: 'Stream',
			parent: 4,
			settings: {}
		}
			
	}
```

**Comment by nnm103** [comment]
Hi @t2t2  Do I need to do anything with the settings.js in store/modules?

**Comment by nnm103** [comment]
@t2t2 I did an experiment and replaced the first two panels with something other than 'Scenes' and then nothing show's up in the build when I reset the view.  It seems like it will not take anything else but those two first panels. Is there a setting somewhere else that I need to change or apply these panels to?

**Comment by t2t2** [comment]
Make the parent value of panels that aren't first level's children a string, (or for all of them but then also update state.tabs root to a string) it's a type issue that I just noticed while doing typescript conversion.

```js
// ...
		3: {
			type: 'Grid',
			parent: 1,
			settings: {direction: 'row'}
		},
		4: {
			type: 'Grid',
			parent: '3',
			settings: {direction: 'column'}
		},
// ...
```

**Comment by nnm103** [comment]
Thank you very much @t2t2. I was pulling my hair out trying to make this work.  Last questions... I hope!!.  Would like to modify theme to be dark-mode by default and also hardcore url and password so if I go to localhost it goest right to the page. 

Thank you again!

**Comment by t2t2** [comment]
Default theme: (dark is `dark-blue`) https://github.com/t2t2/obs-tablet-remote/blob/3da5587749df3092402f13968487f2d2ca2f560c/src/store/modules/settings.js#L6

**Comment by nnm103** [comment]
Thank you.
