### ISSUE TITLE
Cannot make a twitch chat embed

### ISSUE THREAD

**Issue by GoudronViande24** [t2t2/obs-tablet-remote#91]
The iframe is broken

![image](https://user-images.githubusercontent.com/42936037/103929805-d0781780-50eb-11eb-8709-80c0cda9b68d.png)

Here is what appears in the console

![image](https://user-images.githubusercontent.com/42936037/103929927-f9001180-50eb-11eb-906c-7711f4bc0bd8.png)

**Comment by rjmxtechnology** [comment]
In Firefox 84.0.2 on Linux (could be other versions and OSes too) Twitch chat also doesn't work in the frame when trying to embed it. Similar to Chrome/Chromium this is shown 
![image](https://user-images.githubusercontent.com/12705139/104116696-9e7bd680-52e0-11eb-9dc1-35511993c9e7.png)

**Comment by Artivain** [comment]
It looks like it's done because of mixed content (http with https).

**Comment by t2t2** [comment]
For the url in original issue It's the [`X-Frame-Options: SAMEORIGIN` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) on that specific url (popout chat), same for the dashboard.twitch.tv url in @rjmxtechnology)

`https://www.twitch.tv/embed/og3nelive/chat?parent=t2t2.github.io` would work but twitch adds header `Content-Security-Policy: frame-ancestors https://t2t2.github.io` which requires https, so only suggestion here is to spam https://dev.twitch.tv/docs/embed#providing-feedback

**Comment by rjmxtechnology** [comment]
Gotcha, that's unfortunate, but no worries. I still appreciate the great capability this tool offers @t2t2.

**Comment by Artivain** [comment]
> For the url in original issue It's the [`X-Frame-Options: SAMEORIGIN` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) on that specific url (popout chat), same for the dashboard.twitch.tv url in @rjmxtechnology)
> 
> `https://www.twitch.tv/embed/og3nelive/chat?parent=t2t2.github.io` would work but twitch adds header `Content-Security-Policy: frame-ancestors https://t2t2.github.io` which requires https, so only suggestion here is to spam https://dev.twitch.tv/docs/embed#providing-feedback

Thanks !
This tool still have all I need, I can open the twitch chat in another window, it's just a little less practical.
